# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Майстриня
email: your-email@domain.com
description: Шукаєте якісний та швидкий сервіс по ремонту одягу? Тоді вам до нас. Швейна майстерня "Майстриня" в Черкасах
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maystrunya.ck.ua" # the base hostname & protocol for your site
twitter_username: maystrynya
github_username: galyakorpan
facebook_username: maystrunya
vkontakte_username: maystrunya

# Build settings
gems:
  - jekyll-sitemap
